#!/bin/bash

if [[ ! -d /run/nordvpn ]]; then
  mkdir -m 0770 /run/nordvpn
fi

if [[ -n ${NORDVPN_MESHNET_DEBUG} ]]; then
  exec s6-notifyoncheck -n 60 -d /usr/sbin/nordvpnd > /proc/1/fd/1 2>&1
else
  exec s6-notifyoncheck -n 60 -d /usr/sbin/nordvpnd > /dev/null 2>&1
fi