#!/bin/bash

if [[ ! -d /run/nordvpn ]]; then
  mkdir -m 0770 /run/nordvpn
fi

if [[ -n ${NORDVPN_MESHNET_DEBUG} ]]; then
  exec /usr/sbin/nordvpnd > /var/lib/nordvpn/nordvpnd.log 2>&1
else
  exec /usr/sbin/nordvpnd > /dev/null 2>&1
fi